"""
Phase C - profile the real CSVs into docs/DATA_PROFILE.md.

This exists because the schema comments shipped inside the query files describe
tables that do not exist in the actual Kaggle downloads (no merchants table in
creditcardfraud, no churn_date in telco-customer-churn, and so on). Every
downstream decision - which tables to build, which queries can be written - is
mapped from this profile rather than from those comments.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sqlutil import DATA_RAW, DOCS_DIR, PROJECTS, clean_identifier, human  # noqa: E402

ENCODINGS = ["utf-8", "utf-8-sig", "latin-1", "cp1252"]


def read_csv_resilient(path: Path, nrows: int | None = None) -> tuple[pd.DataFrame, str]:
    """Kaggle CSVs are inconsistently encoded; try the usual suspects in order."""
    last: Exception | None = None
    for enc in ENCODINGS:
        try:
            df = pd.read_csv(
                path,
                nrows=nrows,
                encoding=enc,
                low_memory=False,
                on_bad_lines="warn",
            )
            return df, enc
        except (UnicodeDecodeError, pd.errors.ParserError) as exc:
            last = exc
    raise RuntimeError(f"could not read {path.name}: {last}")


def profile_frame(df: pd.DataFrame) -> pd.DataFrame:
    rows = len(df)
    out = []
    for col in df.columns:
        s = df[col]
        nulls = int(s.isna().sum())
        distinct = int(s.nunique(dropna=True))
        sample = s.dropna().head(3).tolist()
        rng = ""
        if pd.api.types.is_numeric_dtype(s) and distinct:
            rng = f"{s.min():.4g} .. {s.max():.4g}"
        out.append(
            {
                "column": str(col),
                "sql_name": clean_identifier(str(col)),
                "dtype": str(s.dtype),
                "null_pct": f"{100.0 * nulls / rows:.1f}%" if rows else "-",
                "distinct": distinct,
                "range": rng,
                "samples": ", ".join(str(v)[:28] for v in sample),
            }
        )
    return pd.DataFrame(out)


def main() -> int:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    if not DATA_RAW.exists() or not any(DATA_RAW.rglob("*.csv")):
        print("No CSVs under data/raw/. Run scripts/fetch.py first.")
        return 1

    lines: list[str] = [
        "# Real Dataset Profile",
        "",
        "Generated by `scripts/profile_data.py` from the actual downloaded CSVs.",
        "This file is the source of truth for the query rewrite - not the schema",
        "comments in the original query files, which describe tables that do not exist.",
        "",
    ]

    for project, (dataset_id, label) in PROJECTS.items():
        pdir = DATA_RAW / project
        csvs = sorted(pdir.rglob("*.csv")) if pdir.exists() else []
        lines += [f"## {project} - {label}", "", f"Kaggle: `{dataset_id}`", ""]
        if not csvs:
            lines += ["> **Not downloaded.**", ""]
            print(f"[warn] {project}: no CSVs")
            continue

        for csv in csvs:
            try:
                df, enc = read_csv_resilient(csv)
            except RuntimeError as exc:
                lines += [f"### `{csv.name}` - UNREADABLE", "", f"> {exc}", ""]
                print(f"[fail] {csv.name}: {exc}")
                continue

            prof = profile_frame(df)
            lines += [
                f"### `{csv.name}`",
                "",
                f"- rows: **{human(len(df))}**  |  columns: **{len(df.columns)}**  "
                f"|  encoding: `{enc}`  |  size: {csv.stat().st_size/1_048_576:.1f} MB",
                f"- suggested table name: `raw_{clean_identifier(csv.stem)}`",
                "",
                "| column | sql_name | dtype | null% | distinct | range | samples |",
                "|---|---|---|---|---|---|---|",
            ]
            for _, r in prof.iterrows():
                lines.append(
                    f"| `{r['column']}` | `{r['sql_name']}` | {r['dtype']} | {r['null_pct']} "
                    f"| {human(r['distinct'])} | {r['range']} | {r['samples']} |"
                )
            lines.append("")
            print(f"[ok]   {project:22s} {csv.name:44s} {human(len(df)):>10s} rows x {len(df.columns)} cols")

    out = DOCS_DIR / "DATA_PROFILE.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
